config/routes.rb
Rails.application.routes.draw do
  resources :list_items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list_item.rb
class ListItem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController

  def index
    @list_items = ListItem.all
  end

  def new
    @list_item = ListItem.new
  end


  def create
    @list_item = ListItem.new(list_item_params)
    @list_item.save
    redirect_to list_items_path
  end

  private

    def list_item_params
      params.require(:list_item).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopping List</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="app-container">
    <%= yield %>
    <div>
  </body>
</html>

app/views/list_items/index.html.erb
<h1>Shopping List</h1>


  <% @list_items.each do |list_item| %>
      <li><%= list_item.name %></li>
  <% end %>

  <br>

<%= link_to 'Add Item', new_list_item_path %>

app/views/list_items/new.html.erb
<h1>Add Item to Shopping List</h1>

<%= form_for @list_item do |form| %>

    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.submit class: 'btn-primary' %>

<% end %>

<%= link_to 'Back to Shopping List', list_items_path %>